import CArdk
import simd
import UIKit
import Foundation

/// Contains depth estimation results from the NSDK depth processing system.
///
/// ## Overview
///
/// Depth results are generated by the depth processing system and include:
/// - Disparity maps for depth estimation. Unlike direct depth maps that provide distance
///   values in meters, disparity maps contain pixel offset values that represent relative
///   depth differences. These values must be converted to actual depth using camera
///   intrinsic parameters and baseline information.
/// - Camera pose and orientation information
/// - Camera intrinsic parameters for coordinate transformations
/// - Error status and metadata
public class DepthResult: AwarenessImageResult {
    /// The device orientation when the depth data was captured.
    ///
    /// This orientation information is crucial for correctly interpreting the depth
    /// image and applying the appropriate coordinate transformations.
    public var orientation: UIInterfaceOrientation

    /// The minimum disparity value in the depth map.
    ///
    /// Lower disparity values indicate objects farther from the camera.
    public var disparity_min: Float

    /// The maximum disparity value in the depth map.
    ///
    /// Higher disparity values indicate objects closer to the camera.
    public var disparity_max: Float

    init(fromC cData: ARDK_DepthResult, owner: ResourceOwner? = nil) {
        orientation = UIInterfaceOrientation(fromC: cData.orientation)
        disparity_min = cData.disparity_min
        disparity_max = cData.disparity_max

        super.init(
            context: cData.context,
            image: RawImage(fromC: cData.image),
            owner: owner
        )
    }
}
